# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='users_like',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
