# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:27
from __future__ import unicode_literals
from django.db import migrations, models
from django.apps import apps
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

translatable_models = {
    'Category': ['name', 'slug'],
    'Product': ['name', 'slug', 'description'],
}

def _get_translation(obj, MyModelTranslation):
    translations = MyModelTranslation.objects.filter(master_id=obj.pk)
    try:
        # let's try a default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except:
        # hoping that there is a single translation (only one language_code)
        return translations.get()

def forwards_func(apps, schema_editor):
    for model, fields in translatable_models.items():
        Model = apps.get_model('shop', model)  # get the 'original' model
        ModelTranslation = apps.get_model('shop', '{}Translation'.format(model))  # get the translation model

        # For every object (relation) in the database, get its value and copy it over to the translated table (create a new relation in the translated table)
        for obj in Model.objects.all():
            translation_fields = {field: getattr(obj, field) for field in fields}  # field_name : field_value
            translation = ModelTranslation.objects.create(
                    master_id=obj.pk,
                    language_code=settings.LANGUAGE_CODE,
                    **translation_fields)

def backwards_func(apps, schema_editor):
    for model, fields in translatable_models.items():
        Model = apps.get_model('shop', model)
        ModelTranslation = apps.get_model('shop', '{}Translation'.format(model))

        # Grab the translated field value from the translated table and set our 'original' model's value to that value
        for obj in Model.objects.all():
            translation = _get_translation(obj, ModelTranslation)
            for field in fields:
                setattr(obj, field, getattr(translaiton, field))

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_translation_model'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_code=backwards_func)
    ]
